name: dragon_logs
description: An efficient cross-platform Flutter log storage framework with minimal dependencies.
version: 1.0.1

repository: https://github.com/KomodoPlatform/dragon_logs_flutter
homepage: https://komodoplatform.com


environment:
  sdk: '>=2.14.0 <4.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependencies:
  flutter:
      sdk: flutter

  flutter_localizations:
    sdk: flutter

  # No longer needed since replaced by file storage and web OPFS storage.
  # Could be used as a fallback for storage on web for older browsers.
  # # Secure code review approved via PR #1106
  # hive:
  #   git:
  #     url: https://github.com/KomodoPlatform/hive.git
  #     path: hive/
  #     ref: 470473ffc1ba39f6c90f31ababe0ee63b76b69fe #2.2.3

  # Approved via K-W PR  #1106
  share_plus: ^7.0.2 # TODO: request review of latest version
    
  # ====== Pending Secure code review ======
  # archive: ^3.3.7
  file_system_access_api: ^1.1.0

  # ====== Flutter.dev/Dart.dev approved ======
  # Secure review for Flutter.dev/Dart.dev packages not strictly required since
  # they are Google/Dart products, but still recommended.
  
  intl: ^0.18.1
  path_provider: ^2.1.1
  path: ^1.8.3
  js: ^0.6.7
